version: '3.8'

services:
  user-service:
    image: ${DOCKERHUB_USERNAME:-local}/user-service:latest
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: ${DB_HOST:-microservices-project-db.cc5akoumm873.us-east-1.rds.amazonaws.com}
      DB_PORT: "5432"
      DB_NAME: "microservicesdb"
      DB_USER: "dbadmin"
      DB_PASSWORD: "ChangeMe123!"
      JAVA_OPTS: "-Xmx160m -Xms64m"
    deploy:
      resources:
        limits:
          memory: 220M

  product-service:
    image: ${DOCKERHUB_USERNAME:-local}/product-service:latest
    build: ./product-service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: ${DB_HOST:-microservices-project-db.cc5akoumm873.us-east-1.rds.amazonaws.com}
      DB_PORT: "5432"
      DB_NAME: "microservicesdb"
      DB_USER: "dbadmin"
      DB_PASSWORD: "ChangeMe123!"
      JAVA_OPTS: "-Xmx160m -Xms64m"
      CLOUD_SQS_PRODUCT_EVENTS_ENABLED: "true"
      CLOUD_SQS_PRODUCT_EVENTS_QUEUE_URL: ${QUEUE_URL}
      AWS_REGION: "us-east-1"
    deploy:
      resources:
        limits:
          memory: 220M

  order-service:
    image: ${DOCKERHUB_USERNAME:-local}/order-service:latest
    build: ./order-service
    ports:
      - "8083:8083"
    environment:
      DB_HOST: ${DB_HOST:-microservices-project-db.cc5akoumm873.us-east-1.rds.amazonaws.com}
      DB_PORT: "5432"
      DB_NAME: "microservicesdb"
      DB_USER: "dbadmin"
      DB_PASSWORD: "ChangeMe123!"
      JAVA_OPTS: "-Xmx160m -Xms64m"
      SERVICES_USER_URL: http://user-service:8081
      SERVICES_PRODUCT_URL: http://product-service:8082
      CLOUD_SQS_PRODUCT_EVENTS_CONSUMER_ENABLED: "true"
      CLOUD_SQS_PRODUCT_EVENTS_CONSUMER_QUEUE_URL: ${DLQ_URL}
      AWS_REGION: "us-east-1"
    deploy:
      resources:
        limits:
          memory: 220M
    depends_on:
      - user-service
      - product-service

  api-gateway:
    image: ${DOCKERHUB_USERNAME:-local}/api-gateway:latest
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xmx128m -Xms64m"
    deploy:
      resources:
        limits:
          memory: 180M
    depends_on:
      - user-service
      - product-service
      - order-service

networks:
  default:
    driver: bridge